#!/usr/bin/env bash
# ============================================================================
# OpenCloudTouch Raspberry Pi Image Builder
# ============================================================================
# Builds ready-to-flash SD card images using pi-gen (official RPi OS builder).
#
# Usage:
#   ./build.sh --arch arm64        # RPi 3/4/5 (64-bit)
#   ./build.sh --arch armhf        # RPi 2/3 (32-bit)
#   ./build.sh --arch all          # Both architectures
#   ./build.sh --arch arm64 --clean  # Clean build (remove pi-gen cache)
#
# Requirements:
#   - Docker (for containerized pi-gen build)
#   - ~10 GB free disk space
#   - Internet access (downloads base OS + packages)
# ============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PI_GEN_DIR="${SCRIPT_DIR}/pi-gen"
PI_GEN_REPO="https://github.com/RPi-Distro/pi-gen.git"
PI_GEN_BRANCH=""  # Set per-arch in build_image()
OUTPUT_DIR="${SCRIPT_DIR}/output"
OCT_VERSION="${OCT_VERSION:-latest}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# ============================================================================
# Parse arguments
# ============================================================================
ARCH=""
CLEAN=false

while [[ $# -gt 0 ]]; do
    case $1 in
        --arch)
            ARCH="$2"
            shift 2
            ;;
        --clean)
            CLEAN=true
            shift
            ;;
        --version)
            OCT_VERSION="$2"
            shift 2
            ;;
        -h|--help)
            echo "Usage: $0 --arch <arm64|armhf|all> [--clean] [--version <tag>]"
            echo ""
            echo "Options:"
            echo "  --arch <arch>     Target architecture: arm64, armhf, or all"
            echo "  --clean           Clean pi-gen work directory before build"
            echo "  --version <tag>   OCT Docker image tag (default: latest)"
            exit 0
            ;;
        *)
            log_error "Unknown option: $1"
            exit 1
            ;;
    esac
done

if [[ -z "$ARCH" ]]; then
    log_error "Architecture required. Use: --arch <arm64|armhf|all>"
    exit 1
fi

# ============================================================================
# Validate prerequisites
# ============================================================================
check_prerequisites() {
    log_info "Checking prerequisites..."

    if ! command -v docker &>/dev/null; then
        log_error "Docker is required but not installed."
        exit 1
    fi

    if ! docker info &>/dev/null; then
        log_error "Docker daemon is not running."
        exit 1
    fi

    log_info "Prerequisites OK"
}

# ============================================================================
# Clone or update pi-gen
# ============================================================================
setup_pigen() {
    local branch="$1"
    if [[ ! -d "$PI_GEN_DIR" ]]; then
        log_info "Cloning pi-gen (branch: $branch)..."
        git clone --depth 1 --branch "$branch" "$PI_GEN_REPO" "$PI_GEN_DIR"
    else
        log_info "Updating pi-gen (branch: $branch)..."
        cd "$PI_GEN_DIR"
        git fetch --depth 1 origin "$branch"
        git checkout FETCH_HEAD
        cd "$SCRIPT_DIR"
    fi
}

# ============================================================================
# Generate pi-gen config for a specific architecture
# ============================================================================
generate_config() {
    local arch="$1"
    local config_file="${PI_GEN_DIR}/config"

    log_info "Generating pi-gen config for ${arch}..."

    # Architecture-specific settings
    local target_hostname="opencloudtouch"
    local img_name="opencloudtouch-${arch}"

    cat > "$config_file" << EOF
# OpenCloudTouch pi-gen configuration
# Auto-generated by build.sh — do not edit manually

IMG_NAME="${img_name}"
RELEASE=trixie
TARGET_HOSTNAME="${target_hostname}"
FIRST_USER_NAME=oct
FIRST_USER_PASS="opencloudtouch"
ENABLE_SSH=1
LOCALE_DEFAULT=en_GB.UTF-8
KEYBOARD_KEYMAP=us
KEYBOARD_LAYOUT="English (US)"
TIMEZONE_DEFAULT=Europe/Berlin
WPA_COUNTRY=DE

# DISABLE desktop, multimedia, etc. — we want a headless appliance
STAGE_LIST="stage0 stage1 stage2 stage-opencloudtouch"

# Architecture
EOF

    if [[ "$arch" == "arm64" ]]; then
        echo 'ARCH=arm64' >> "$config_file"
    else
        echo 'ARCH=armhf' >> "$config_file"
    fi

    # Skip stages 3-5 (desktop environment, etc.)
    touch "${PI_GEN_DIR}/stage3/SKIP" 2>/dev/null || true
    touch "${PI_GEN_DIR}/stage4/SKIP" 2>/dev/null || true
    touch "${PI_GEN_DIR}/stage5/SKIP" 2>/dev/null || true

    # Skip image export for base stages (only export our custom stage)
    touch "${PI_GEN_DIR}/stage0/SKIP_IMAGES" 2>/dev/null || true
    touch "${PI_GEN_DIR}/stage1/SKIP_IMAGES" 2>/dev/null || true
    touch "${PI_GEN_DIR}/stage2/SKIP_IMAGES" 2>/dev/null || true
}

# ============================================================================
# Install custom stage into pi-gen
# ============================================================================
install_stage() {
    local stage_target="${PI_GEN_DIR}/stage-opencloudtouch"

    log_info "Installing OpenCloudTouch stage..."

    # Remove old stage if exists
    rm -rf "$stage_target"

    # Copy our custom stage
    cp -r "${SCRIPT_DIR}/stage-opencloudtouch" "$stage_target"

    # Copy embedded files
    mkdir -p "${stage_target}/01-configure-oct/files"
    cp "${SCRIPT_DIR}/files/docker-compose.yml" "${stage_target}/01-configure-oct/files/"
    cp "${SCRIPT_DIR}/files/oct-firstboot.sh" "${stage_target}/01-configure-oct/files/"
    cp "${SCRIPT_DIR}/files/oct-firstboot.service" "${stage_target}/01-configure-oct/files/"
    cp "${SCRIPT_DIR}/files/oct-update.sh" "${stage_target}/01-configure-oct/files/"
    cp "${SCRIPT_DIR}/files/oct-config.txt" "${stage_target}/01-configure-oct/files/"

    # Export image from our stage
    touch "${stage_target}/EXPORT_IMAGE"
    touch "${stage_target}/EXPORT_NOOBS"

    # Set OCT version in compose file
    if [[ "$OCT_VERSION" != "latest" ]]; then
        sed -i "s|ghcr.io/scheilch/opencloudtouch:latest|ghcr.io/scheilch/opencloudtouch:${OCT_VERSION}|g" \
            "${stage_target}/01-configure-oct/files/docker-compose.yml"
    fi

    log_info "Custom stage installed"
}

# ============================================================================
# Build image
# ============================================================================
build_image() {
    local arch="$1"

    # arm64 branch = 64-bit kernels only; master = 32-bit kernels for RPi 2
    if [[ "$arch" == "armhf" ]]; then
        PI_GEN_BRANCH=master
    else
        PI_GEN_BRANCH=arm64
    fi

    log_info "Building ${arch} image (pi-gen branch: ${PI_GEN_BRANCH})..."

    setup_pigen "$PI_GEN_BRANCH"
    generate_config "$arch"
    install_stage

    if [[ "$CLEAN" == "true" ]]; then
        log_info "Cleaning pi-gen work directory..."
        rm -rf "${PI_GEN_DIR}/work" "${PI_GEN_DIR}/deploy"
    fi

    cd "$PI_GEN_DIR"

    # Build using Docker (works on any Linux and in CI)
    ./build-docker.sh

    cd "$SCRIPT_DIR"

    # Collect output
    mkdir -p "$OUTPUT_DIR"
    local img_file
    img_file=$(find "${PI_GEN_DIR}/deploy" -name "opencloudtouch-${arch}*.img.xz" -type f | head -1)

    if [[ -z "$img_file" ]]; then
        # Try uncompressed
        img_file=$(find "${PI_GEN_DIR}/deploy" -name "opencloudtouch-${arch}*.img" -type f | head -1)
        if [[ -n "$img_file" ]]; then
            log_info "Compressing image..."
            xz -9 -T0 "$img_file"
            img_file="${img_file}.xz"
        else
            log_error "No image file found in ${PI_GEN_DIR}/deploy/"
            ls -la "${PI_GEN_DIR}/deploy/" || true
            exit 1
        fi
    fi

    local output_name="opencloudtouch-${arch}-${OCT_VERSION}.img.xz"
    cp "$img_file" "${OUTPUT_DIR}/${output_name}"

    # Generate checksums
    cd "$OUTPUT_DIR"
    sha256sum "${output_name}" > "${output_name}.sha256"
    cd "$SCRIPT_DIR"

    log_info "Image built: ${OUTPUT_DIR}/${output_name}"
    log_info "SHA256: $(cat "${OUTPUT_DIR}/${output_name}.sha256")"
}

# ============================================================================
# Main
# ============================================================================
main() {
    log_info "OpenCloudTouch Raspberry Pi Image Builder"
    log_info "Architecture: ${ARCH}"
    log_info "OCT Version: ${OCT_VERSION}"
    echo ""

    check_prerequisites

    case "$ARCH" in
        arm64)
            build_image arm64
            ;;
        armhf)
            build_image armhf
            ;;
        all)
            build_image arm64
            # Clean work dir between builds to avoid architecture conflicts
            CLEAN=true
            build_image armhf
            ;;
        *)
            log_error "Invalid architecture: ${ARCH}. Use: arm64, armhf, or all"
            exit 1
            ;;
    esac

    echo ""
    log_info "=========================================="
    log_info "Build complete! Output files:"
    ls -lh "${OUTPUT_DIR}"/opencloudtouch-*.img.xz 2>/dev/null || true
    log_info "=========================================="
}

main
